SELECT ID, (
    CASE WHEN ((RANK () OVER(ORDER BY SIZE_OF_COLONY))/(SELECT COUNT(*) FROM ECOLI_DATA)) <= 0.25 THEN 'LOW'
        WHEN ((RANK () OVER(ORDER BY SIZE_OF_COLONY))/(SELECT COUNT(*) FROM ECOLI_DATA)) <= 0.50 THEN 'MEDIUM'
        WHEN ((RANK () OVER(ORDER BY SIZE_OF_COLONY))/(SELECT COUNT(*) FROM ECOLI_DATA)) <= 0.75 THEN 'HIGH'
    ELSE 'CRITICAL'
    END) AS COLONY_NAME
FROM ECOLI_DATA ORDER BY ID