-- 코드를 입력하세요

SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE FROM REST_INFO RIGHT JOIN 
(SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW
GROUP BY REST_ID) AS STAR
ON REST_INFO.REST_ID = STAR.REST_ID
WHERE REST_INFO.ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, FAVORITES DESC
