-- 코드를 입력하세요
SELECT A.CATEGORY, B.MAX_PRICE, A.PRODUCT_NAME 
FROM FOOD_PRODUCT AS A 
    INNER JOIN 
    (SELECT CATEGORY, MAX(PRICE) AS 'MAX_PRICE' FROM FOOD_PRODUCT GROUP BY CATEGORY) 
    AS B ON A.CATEGORY = B.CATEGORY
WHERE A.PRICE = B.MAX_PRICE AND A.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY B.MAX_PRICE DESC